baseURL = "https://davecap.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
title = "davecap's place"
theme = "harbor"
footnoteReturnLinkContents = "^"
copyright = "© davecap.com"

paginate = 10

disqusShortName = "davecap"
googleAnalytics = "UA-25251051-1"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[Author]
  name = "David Caplan"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "about"
  weight = 3

[params.logo]
  url = "icon.png"
  width = 50
  height = 50
  alt = "Logo"
