baseURL = "https://davecap.com/"
languageCode = "en-us"
title = "davecap's place"
theme = "anubis"

paginate = 10
disqusShortname = "davecap"
googleAnalytics = "UA-25251051-1"

copyright = "© davecap.com"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1
